"""Subset Material Symbols Outlined to the icons the Axis portal uses.

Produces a tiny same-origin woff2 (keeps the FILL/wght/GRAD/opsz axes so the
Icon component's font-variation-settings still work) plus a name->codepoint TS
map so the portal can render icons by codepoint (no Google CDN, no ligatures).
"""
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = os.path.dirname(os.path.abspath(__file__))
PORTAL = os.path.dirname(HERE)
TTF = os.path.join(HERE, "MaterialSymbols.ttf")
CODEPOINTS = os.path.join(HERE, "codepoints.txt")

# Icons actually referenced in the portal (verified by grep) ...
USED = """
account_balance_wallet add add_shopping_cart arrow_back chevron_right dashboard
description download help info list logout menu numbers payments person
picture_as_pdf receipt_long schedule search sell settings swap_horiz task_alt
trending_down trending_up verified verified_user warning
""".split()

# ... plus a buffer of common icons so future edits "just work" without a
# re-subset. Tiny cost; big robustness win.
BUFFER = """
close check check_circle cancel error expand_more expand_less more_vert
more_horiz edit delete visibility visibility_off location_on calendar_today
calendar_month mail call home refresh filter_list sort north_east south_east
trending_flat account_circle notifications lock login arrow_forward
arrow_upward arrow_downward arrow_drop_down open_in_new content_copy print
attach_file upload folder paid savings receipt currency_exchange
account_balance credit_card history done done_all pending send star
help_outline dark_mode light_mode chevron_left keyboard_arrow_down
keyboard_arrow_up close_small refresh
""".split()

names = list(dict.fromkeys(USED + BUFFER))  # de-dupe, keep order

# Parse the codepoints file: "iconname e8b6"
name_to_cp = {}
with open(CODEPOINTS, encoding="utf-8") as fh:
    for line in fh:
        line = line.strip()
        if not line:
            continue
        n, hexcp = line.split()
        name_to_cp[n] = int(hexcp, 16)

resolved = {}
missing = []
for n in names:
    if n in name_to_cp:
        resolved[n] = name_to_cp[n]
    else:
        missing.append(n)

if missing:
    print("WARNING: names not found in codepoints file:", ", ".join(missing))

# Subset the variable font to just these codepoints, keeping the axes.
unicodes = sorted(set(resolved.values()))
options = subset.Options()
options.flavor = "woff2"
options.layout_features = []          # we render by codepoint, no ligatures
options.name_IDs = []                 # drop the bulky name table
options.glyph_names = False
options.notdef_outline = True
options.recalc_timestamp = False

font = TTFont(TTF)
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=unicodes)
subsetter.subset(font)
# Pin the axes the app never varies (opsz=24, GRAD=0, wght=400) and keep only
# FILL (0..1) — the Icon component toggles fill for active/verified states.
# Done AFTER subsetting (instancing first trips a fontTools gvar KeyError).
instantiateVariableFont(font, {"opsz": 24, "GRAD": 0, "wght": 400}, inplace=True)

out_woff2 = os.path.join(PORTAL, "src", "fonts", "material-symbols-subset.woff2")
font.save(out_woff2)
size_kb = os.path.getsize(out_woff2) / 1024
print(f"Subset: {len(resolved)} icons, {len(unicodes)} glyphs -> {size_kb:.1f} KB woff2")

# Emit the name->codepoint TS map.
lines = [
    "// AUTO-GENERATED by tmp/msym/subset_msym.py — do not edit by hand.",
    "// Material Symbols Outlined codepoints for the icons bundled in the",
    "// self-hosted subset (src/fonts/material-symbols-subset.woff2).",
    "// To add an icon: add its name to subset_msym.py, re-run it, rebuild.",
    "export const ICON_CODEPOINTS: Record<string, string> = {",
]
for n in sorted(resolved):
    lines.append(f'  {n!r}: "\\u{resolved[n]:04x}",'.replace("'", '"'))
lines.append("};")
ts = "\n".join(lines) + "\n"
with open(os.path.join(PORTAL, "src", "components", "ui", "material-symbols-codepoints.ts"), "w", encoding="utf-8") as fh:
    fh.write(ts)
print(f"Wrote TS map with {len(resolved)} entries")
print("USED icons all resolved:" , all(u in resolved for u in USED))
