#!/usr/bin/env python3
"""
import_cedar_csd.py  —  Repeatable Cedar client CSD importer.

WHY: a fresh data migration (raw legacy restore OR clean-schema migration) lands
client records WITHOUT their CSD numbers (the legacy ClientCDSNo column is
nvarchar(20) and the real codes are 23 chars, so they are lost/truncated). This
re-applies them from the firm's authoritative listing.

SOURCE OF TRUTH: BK_Files/Client Listing - Updated CSD.xlsx
  columns: Client Code (= Client_DPA_), Name, ID/Passport, CSD Number, ...
  Keyed by Client_DPA_ (stable legacy PK, preserved by both migration paths).
  To add newly-opened CSD accounts, just update that Excel and re-run this.

USAGE (regenerate the SQL, then run it on the freshly-migrated DB):
  cd BK_Files
  python import_cedar_csd.py
  scp apply_cedar_csd.sql verify_cedar_csd.sql root@<host>:/tmp/
  sqlcmd -S localhost -U sa -P '<pw>' -C -d <NewDB> -b -i /tmp/apply_cedar_csd.sql
  sqlcmd -S localhost -U sa -P '<pw>' -C -d <NewDB>    -i /tmp/verify_cedar_csd.sql
Then in the app: CDS Trade Imports -> open each pending batch -> "Re-run
reconciliation" -> Commit. Works on raw legacy OR clean schema (same dbo.Client).
"""
import csv
import openpyxl
from collections import defaultdict

XLSX = 'Client Listing - Updated CSD.xlsx'
OUT = 'apply_cedar_csd.sql'
CHUNK = 900  # rows per INSERT ... VALUES (SQL Server caps at 1000)


def esc(s):
    return (s or '').replace("'", "''")


def main():
    wb = openpyxl.load_workbook(XLSX, read_only=True, data_only=True)
    ws = wb.active
    rows = []
    blank = 0
    for r in ws.iter_rows(min_row=2, values_only=True):
        code, name, idp, csd = r[0], r[1], r[2], r[3]
        if code is None:
            continue
        try:
            dpa = int(code)
        except (TypeError, ValueError):
            continue
        cds = ('' if csd is None else str(csd)).strip()
        if not cds:
            blank += 1
            continue
        rows.append((dpa, cds, ('' if idp is None else str(idp)).strip()))

    bycsd = defaultdict(list)
    for dpa, cds, _ in rows:
        bycsd[cds].append(dpa)
    dups = {k: v for k, v in bycsd.items() if len(v) > 1}
    lens = sorted({len(c) for _, c, _ in rows})

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        w = f.write
        w("-- ==========================================================================\n")
        w("-- apply_cedar_csd.sql  —  GENERATED by import_cedar_csd.py. Do not hand-edit.\n")
        w("-- Source: %s  (%d clients with a CSD).\n" % (XLSX, len(rows)))
        w("-- Idempotent + transactional + snapshotted. Safe to re-run.\n")
        w("--   sqlcmd -S localhost -U sa -P '<pw>' -C -d <NewDB> -b -i apply_cedar_csd.sql\n")
        w("-- Rollback:\n")
        w("--   UPDATE c SET c.ClientCDSNo=b.ClientCDSNo FROM dbo.Client c\n")
        w("--   JOIN dbo.ClientCDS_backup b ON b.Client_DPA_=c.Client_DPA_;\n")
        w("-- ==========================================================================\n")
        w("SET NOCOUNT ON;\nSET XACT_ABORT ON;\n\n")

        w("-- 1) Widen ClientCDSNo to hold the 23-char CSD codes (idempotent).\n")
        w("IF (SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS\n")
        w("    WHERE TABLE_NAME='Client' AND COLUMN_NAME='ClientCDSNo') < 50\n")
        w("    ALTER TABLE dbo.Client ALTER COLUMN ClientCDSNo nvarchar(50) NULL;\nGO\n\n")

        w("-- 2) Snapshot the pre-apply CSD for rollback (first run wins).\n")
        w("IF OBJECT_ID('dbo.ClientCDS_backup','U') IS NULL\n")
        w("    SELECT Client_DPA_, ClientCDSNo, SYSUTCDATETIME() AS SnapAt\n")
        w("    INTO dbo.ClientCDS_backup FROM dbo.Client;\nGO\n\n")

        w("-- 3) Stage the authoritative (Client_DPA_, CSD, ID/Passport) set.\n")
        w("IF OBJECT_ID('tempdb..#csd') IS NOT NULL DROP TABLE #csd;\n")
        w("CREATE TABLE #csd (Client_DPA_ int PRIMARY KEY, CSDNumber nvarchar(50), IdPass nvarchar(100));\n")
        for i in range(0, len(rows), CHUNK):
            chunk = rows[i:i + CHUNK]
            w("INSERT INTO #csd (Client_DPA_, CSDNumber, IdPass) VALUES\n")
            w(",\n".join("(%d, N'%s', N'%s')" % (dpa, esc(cds), esc(idp)) for dpa, cds, idp in chunk))
            w(";\n")
        w("\n")

        w("-- 4) Apply, keyed by Client_DPA_ (non-deleted clients only).\n")
        w("BEGIN TRAN;\n")
        w("UPDATE c SET c.ClientCDSNo = s.CSDNumber\n")
        w("FROM dbo.Client c JOIN #csd s ON s.Client_DPA_ = c.Client_DPA_\n")
        w("WHERE ISNULL(c.Deleted,0)=0;\n")
        w("DECLARE @applied int = @@ROWCOUNT;\n")
        w("COMMIT;\n\n")

        w("-- 5) Integrity report.\n")
        w("DECLARE @expected int = (SELECT COUNT(*) FROM #csd);\n")
        w("DECLARE @notfound int = (SELECT COUNT(*) FROM #csd s\n")
        w("    WHERE NOT EXISTS (SELECT 1 FROM dbo.Client c WHERE c.Client_DPA_=s.Client_DPA_));\n")
        w("PRINT 'Expected CSD rows from Excel : ' + CAST(@expected AS varchar(12));\n")
        w("PRINT 'Clients updated              : ' + CAST(@applied  AS varchar(12));\n")
        w("PRINT 'Client_DPA_ not found in DB  : ' + CAST(@notfound AS varchar(12)) + '  (id drift / not yet migrated)';\n")
        w("\n-- ID/Passport sanity: where the Excel ID differs from the DB for the same\n")
        w("-- Client_DPA_ (review; may be harmless formatting differences).\n")
        w("SELECT TOP 50 s.Client_DPA_, s.IdPass AS ExcelIdPass, c.ClientIDPass AS DbIdPass, c.ClientName\n")
        w("FROM #csd s JOIN dbo.Client c ON c.Client_DPA_=s.Client_DPA_\n")
        w("WHERE ISNULL(LTRIM(RTRIM(s.IdPass)),'') <> ISNULL(LTRIM(RTRIM(c.ClientIDPass)),'')\n")
        w("ORDER BY s.Client_DPA_;\n")

    print('Wrote %s' % OUT)
    print('  clients with a CSD : %d' % len(rows))
    print('  blank CSD (skipped): %d' % blank)
    print('  CSD length(s)      : %s' % lens)
    print('  duplicate CSDs     : %d (same CSD on >1 client; reconcile is dup-tolerant)' % len(dups))
    for k, v in list(dups.items())[:8]:
        print('     %s -> %s' % (k, v))


if __name__ == '__main__':
    main()
